    <footer>
        <div>
            <h2>Droits</h2>
            <p><a href="index.php?uc=rgpd">RGPD</a></p>
        </div>
        <div>
            <h2>Informations</h2>
            <p><a href="index.php?uc=faq">FAQ</a></p>
            <p><a href="index.php?uc=changelog">Changelog</a></p>
        </div>
        <div>
            <h2>Administration</h2>
            <p><a href="index.php?uc=connexion">Connexion</a></p>
        </div>
        <p>
        <label class="switch">
            <input type="checkbox" onclick="darkMode(true);">
            <span class="slider round"></span>
        </label>
        </p>
        <p class="copy">
            &copy; 2022 Secret du Roi<br>
            Tout droits réservés.
        </p>
        <p>v0.0.4</p>
    </footer>
    <script src="../script/script.js"></script>

    </body>

</html>